#pragma once
#include "infer_train/math/add.hpp"
#include "infer_train/math/sub.hpp"
#include "infer_train/math/mul.hpp"
#include "infer_train/math/div.hpp"
#include "infer_train/math/pow.hpp"
#include "infer_train/math/sqrt.hpp"
#include "infer_train/math/exp.hpp"
#include "infer_train/math/log.hpp"
#include "infer_train/math/abs.hpp"
#include "infer_train/math/clamp.hpp"
#include "infer_train/math/round.hpp"
#include "infer_train/math/reduce.hpp"
// #include "infer_train/math/arg.hpp"
#include "infer_train/math/std_var.hpp"
#include "infer_train/math/matmul.hpp"
