#pragma once
#include "infer_train/math/add_q.hpp"
#include "infer_train/math/sub_q.hpp"
#include "infer_train/math/mul_q.hpp"
#include "infer_train/math/div_q.hpp"
#include "infer_train/math/pow_q.hpp"
#include "infer_train/math/sqrt_q.hpp"
#include "infer_train/math/exp_q.hpp"
#include "infer_train/math/log_q.hpp"
#include "infer_train/math/abs_q.hpp"
#include "infer_train/math/clamp_q.hpp"
#include "infer_train/math/round_q.hpp"
#include "infer_train/math/reduce_q.hpp"
// #include "infer_train/math/arg_q.hpp"
#include "infer_train/math/std_var_q.hpp"
#include "infer_train/math/matmul_q.hpp"
